### ISSUE TITLE
Rotational diffusion of membrane protein

### ISSUE THREAD

**Issue by sperezconesa** [bio-phys/pydiffusion#4]
Hello,

I am trying to study the diffusion of a membrane embeded protein (KcsA specifically). I have been able to replicate the tutorial but I am getting some strange results with my system and I wonder if I am doing something wrong computationally or the theory doesn't work for these cases. I get these plots:
![download](https://user-images.githubusercontent.com/27727343/81177911-b1971380-8fa7-11ea-9a61-4c74811dc9cd.png)
I understand why one of the main component doesn't converge since there is not a lot of vertical rotation of the protein. What I don't understand is why the other components don't converge to 0.25 as in the reset of examples in the paper and the tutorial. 
Thank you very much for your help!
Best regards,
Sergio

**Comment by kain88-de** [comment]
The theory used only works for 3D diffusion. With 2D diffusion in membranes you have strange artifacts, like a diverging diffusion constant. Have a look at the corresponding papers from Martin Vögele and Gerhard Hummer. They also have a paper looking at the rotational diffusion of Membrane proteins. Not sure if the used code is released. It will explain the necessary theory to implement one for yourself.

**Comment by kain88-de** [comment]
Also you need lots of data. I used 10 micro seconds at about 1ns resolution.

**Comment by sperezconesa** [comment]
Thanks a lot for the info. Dor that technique would it be possible to use a 100 simulations of 100ns rather than 1 of 10micro seconds?

**Comment by kain88-de** [comment]
Yeah sure that would work for averaging. There code internally actually splits a single long trajectory into multiple shorter ones. But it splits the trajectories with overlap. For the example from a 10ns trajectory I can get 3 non overlapping pieces of size 3, or 8 overlapping pieces. Of course this introduces some correlation between the pieces but we found that not to have a huge impact on the final result. 

Also 100ns might be short if you want to see the graphs level off. This can happen later for proteins. 

I also encourage you to look at the diffusion in membranes papers from Vögele and Hummer. The diffusion in membranes is very different from free particles.
